### PR TITLE
fix: Resolve UE 5.5 compilation errors with backward compatibility for UE 5.3/5.4Fix UE 5.5 compilation errors with backward compatibility for UE 5.3/5.4

### PR DESCRIPTION
**Pull request by jamesmandrews**
- Make InterchangeOpenUSD plugin dependency optional
- Add version guards for FMetaData -> UMetaData API change in UE 5.5
- Add conditional include for MaterialDomain.h (required in UE 5.5+)
- Guard SetDataLayerIsInitiallyVisible call (removed in UE 5.5)
- Replace direct UNiagaraSystemFactoryNew usage with AssetTools.CreateAsset() for cross-version compatibility

  ---
  Summary

  Fix compilation errors when building the McpAutomationBridge plugin on Unreal Engine 5.5, while maintaining backward compatibility with UE 5.3 and 5.4.

  Changes

  - Make InterchangeOpenUSD plugin dependency optional (not installed by default in all UE 5.5 installations)
  - Add version guards for FMetaData → UMetaData* API change in UE 5.5
  - Add conditional include for MaterialDomain.h (required in UE 5.5+ for EMaterialDomain enum)
  - Guard SetDataLayerIsInitiallyVisible call which was removed in UE 5.5
  - Replace direct UNiagaraSystemFactoryNew factory instantiation with AssetTools.CreateAsset() to fix linker errors

  Related Issues

  Type of Change

  - 🐛 Bug fix (non-breaking change that fixes an issue)

  Testing

  - Tested with Unreal Engine (version: 5.5)
  - Tested MCP client integration (client: ___)
  - Added/updated tests

  Pre-Merge Checklist

  - Code follows project style guidelines
  - Self-reviewed the code
  - Updated relevant documentation (if needed)
  - Added/updated tests (if applicable)
  - CI passes

## Summary by CodeRabbit

* **Bug Fixes**
  * Improved compatibility with Unreal Engine 5.5+ by updating metadata handling, data layer visibility, and material domain includes.

* **Chores**
  * Refined Niagara and effect asset creation to use the standardized asset tools pipeline.
  * Adjusted plugin manifest to mark the InterchangeOpenUSD entry as optional.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

**Comment by ChiR24** [comment]
Hey @MuzammilMushtaque! 👋

Thanks for working on UE 5.5 compatibility! I tested this PR across multiple engine versions and found one issue:

---

### `FMetaData`/`UMetaData` Version Guard

I compared the engine source across versions:

| UE Version | `Package->GetMetaData()` Returns |
|------------|----------------------------------|
| 5.3, 5.4, 5.5 | `UMetaData*` |
| 5.6, 5.7 | `FMetaData&` |

The API change happened in **UE 5.6**, not 5.5. The current guard causes build failures on 5.6+:

```
error C2065: 'UMetaData': undeclared identifier
```

Here's the fix:

```cpp
// Change from:
#if ENGINE_MAJOR_VERSION == 5 && ENGINE_MINOR_VERSION >= 5

// To:
#if ENGINE_MAJOR_VERSION > 5 || (ENGINE_MAJOR_VERSION == 5 && ENGINE_MINOR_VERSION >= 6)
    // UE 5.6+ returns FMetaData&
    FMetaData& Meta = Package->GetMetaData();
    Meta.SetValue(Asset, *Key, *ValueString);
#else
    // UE 5.3, 5.4, 5.5 return UMetaData*
    UMetaData* Meta = Package->GetMetaData();
    if (Meta) Meta->SetValue(Asset, *Key, *ValueString);
#endif
```

This needs to be fixed in both locations in `McpAutomationBridge_AssetWorkflowHandlers.cpp` (around lines 1118 and 2856).

---

### Build Test Results

| UE Version | Status |
|------------|--------|
| 5.5 | ✅ Passes |
| 5.6 | ❌ Fails - `'UMetaData': undeclared identifier` |

---

Happy to help if you have any questions! 🙂

**Comment by jamesmandrews** [comment]
I've had claude update the other locations, I'll push later and pull the repo on my windows machine later and double check that it's working there, my mac drive is small currently only have 5.5 on it, I'll see what I can do about testing other version on this over the weekend.

**Comment by ChiR24** [comment]
Hi @jamesmandrews,

Thanks for this fix! These changes have been incorporated into **PR #183** which extends the compatibility to cover **UE 5.0 through 5.7**.

Closing this in favor of #183. Appreciate your contribution! 🙏
